name: sar3d
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2024.7.4=hbcca054_0
  - certifi=2024.7.4=pyhd8ed1ab_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - conda-pack=0.8.0=pyhd8ed1ab_0
  - cryptography=39.0.1=py39h9ce1e76_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  # - cudatoolkit=11.7
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py39h06a4308_0
  - flit-core=3.8.0=py39h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py39h06a4308_0
  - ilmbase=2.5.5=h780b84a_0
  - imath=3.1.7=h3eb15da_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.1.2=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.6.0.25=0
  - libcurand=10.3.2.56=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=12.2.0=h65d4601_19
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=16.0.1=h417c0b6_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py39h7f8727e_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.2.1=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.8.4=py39h06a4308_1
  - openexr=3.1.7=h5c7bc04_0
  - openexr-python=1.3.9=py39hbd9bb45_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1w=hd590300_0
  - packaging=23.1
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py39h6a678d5_0
  - pip=24.2
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.16=h7a1cb2a_2
  - python_abi=3.9=2_cp39
  - pytorch=2.0.0=py3.9_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_3
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - setuptools=65.6.3=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.1=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.11.1=py39h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd8ed1ab_0
  - torchaudio=2.0.0=py39_cu117
  - torchtriton=2.0.0=py39
  - torchvision=0.15.0=py39_cu117
  - typing_extensions=4.12.2=pyha770c72_0
  - urllib3=1.26.14=py39h06a4308_0
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - absl-py==2.1.0
      - accelerate==0.31.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - antialiased-cnns==0.3
      - antlr4-python3-runtime==4.9.3
      - anyio==4.3.0
      - anykeystore==0.2
      - apex
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - babel==2.15.0
      - backcall==0.2.0
      - beartype==0.18.5
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - blobfile==2.1.1
      - braceexpand==0.1.7
      - cachetools==5.3.3
      - click==8.1.7
      - clip==0.2.0
      - cmake==3.29.3
      - coloredlogs==15.0.1
      - comm==0.1.4
      - contourpy==1.1.0
      - cryptacular==1.6.2
      - cycler==0.11.0
      - debugpy==1.8.1
      - defusedxml==0.7.1
      - diffusers==0.33.1
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - docstring-parser==0.16
      - einops==0.6.0
      - exceptiongroup==1.1.3
      - fairscale==0.4.13
      - fastjsonschema==2.18.0
      - filterpy==1.4.5
      - flatbuffers==25.2.10
      - fonttools==4.42.1
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2023.9.2
      - ftfy==6.1.1
      - gdown==4.4.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - google-auth==2.17.3
      - google-auth-oauthlib==1.0.0
      - greenlet==3.1.1
      - grpcio==1.53.0
      - h11==0.14.0
      - h5py==3.13.0
      - hf-xet==1.1.2
      - httpcore==1.0.4
      - httpx==0.27.0
      - huggingface-hub==0.32.3
      - humanfriendly==10.0
      - hupper==1.12.1
      - imageio==2.27.0
      - imageio-ffmpeg==0.4.8
      - importlib-metadata==6.4.1
      - importlib-resources==6.0.1
      - ipdb==0.12.3
      - ipykernel==6.25.1
      - ipython==8.12.3
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - jaxtyping==0.2.36
      - jedi==0.18.2
      - joblib==1.2.0
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - jupyter==1.0.0
      - jupyter-client==8.3.0
      - jupyter-console==6.6.3
      - jupyter-core==5.3.1
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.2
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.1.2
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.24.0
      - jupyterlab-widgets==3.0.10
      - kiui==0.2.7
      - kiwisolver==1.4.4
      - kornia==0.6.11
      - lazy-loader==0.2
      - lightning-utilities==0.11.2
      - lit==18.1.6
      - llvmlite==0.41.0
      - lmdb==1.4.1
      - lpips==0.1.4
      - lxml==4.9.2
      - lz4==4.3.3
      - markdown==3.4.3
      - matplotlib==3.7.2
      - matplotlib-inline==0.1.6
      - mc-bin-client==1.0.1
      - mistune==3.0.1
      - ml-dtypes==0.2.0
      - moviepy==2.0.0
      - mrcfile==1.5.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - nbclient==0.8.0
      - nbconvert==7.16.6
      - nbformat==5.9.2
      - nest-asyncio==1.5.7
      - ninja==1.11.1
      - notebook==7.1.1
      - notebook-shim==0.2.3
      - numba==0.58.0
      - numpy==1.25.0
      # - nvdiffrast
      # - nvidia-cublas-cu11==11.10.3.66
      # - nvidia-cublas-cu12==12.1.3.1
      # - nvidia-cuda-cupti-cu11==11.7.101
      # - nvidia-cuda-cupti-cu12==12.1.105
      # - nvidia-cuda-nvcc-cu11==11.8.89
      # - nvidia-cuda-nvrtc-cu11==11.7.99
      # - nvidia-cuda-nvrtc-cu12==12.1.105
      # - nvidia-cuda-runtime-cu11==11.7.99
      # - nvidia-cuda-runtime-cu12==12.1.105
      # - nvidia-cudnn-cu11==8.5.0.96
      # - nvidia-cudnn-cu12==8.9.2.26
      # - nvidia-cufft-cu11==10.9.0.58
      # - nvidia-cufft-cu12==11.0.2.54
      # - nvidia-curand-cu11==10.2.10.91
      # - nvidia-curand-cu12==10.3.2.106
      # - nvidia-cusolver-cu11==11.4.0.1
      # - nvidia-cusolver-cu12==11.4.5.107
      # - nvidia-cusparse-cu11==11.7.4.91
      # - nvidia-cusparse-cu12==12.1.0.106
      # - nvidia-nccl-cu11==2.14.3
      # - nvidia-nccl-cu12==2.18.1
      # - nvidia-nvjitlink-cu12==12.4.127
      # - nvidia-nvtx-cu11==11.7.91
      # - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - objprint==0.2.3
      - omegaconf==2.3.0
      - onnxruntime==1.19.2
      - open-clip-torch==2.24.0
      - opencv-python==4.7.0.72
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.3.0
      - overrides==7.4.0
      # - packaging==23.1
      - pandas==2.2.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pastedeploy==3.1.0
      - pathtools==0.1.2
      - pbkdf2==1.3
      - pexpect==4.8.0
      # - pip==24.2
      - pipreqs==0.5.0
      - plaster==1.1.2
      - plaster-pastedeploy==1.0.1
      - platformdirs==3.10.0
      - plyfile==1.0.3
      - point-cloud-utils==0.30.4
      - pooch==1.8.2
      - proglog==0.1.10
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.38
      - protobuf==4.22.3
      - psutil==5.9.4
      - ptflops==0.7
      - pyarrow==17.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycryptodomex==3.17
      - pygments==2.15.1
      - pymatting==1.1.14
      - pymcubes==0.1.4
      - pyparsing==3.0.9
      - pyramid==2.0.2
      - pyramid-mailer==0.15.1
      - pyre-extensions==0.0.23
      - python-dateutil==2.8.2
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - python3-openid==3.2.0
      - pytorch-fid==0.3.0
      - pytorch-lightning==2.2.1
      - pytz==2024.1
      - pywavelets==1.4.1
      - pyyaml==6.0
      - pyzmq==25.1.1
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - referencing==0.30.2
      - regex==2023.3.23
      - rembg==2.0.61
      - repoze-sendmail==4.4.1
      - requests==2.32.3
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.9.2
      - rsa==4.9
      - safetensors==0.4.0
      - scikit-image==0.21.0
      - scikit-learn==1.2.2
      - scikit-video==1.1.11
      - scipy==1.10.0
      - send2trash==1.8.2
      - sentencepiece==0.2.0
      - sentry-sdk==1.24.0
      - setproctitle==1.3.2
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - sqlalchemy==2.0.35
      - tensorboard==2.12.2
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - terminado==0.17.1
      - thop==0.1.1-2209072238
      - threadpoolctl==3.1.0
      - tifffile==2023.4.12
      - timm==0.6.13
      - tinycss2==1.2.1
      - tokenizers==0.15.1
      - tomli==2.0.1
      - torchdiffeq==0.2.3
      - torchmetrics==1.3.2
      - torchtyping==0.1.4
      - tornado==6.3.3
      - tqdm==4.66.5
      - traitlets==5.9.0
      - transaction==5.0
      - transformers==4.37.1
      - translationstring==1.4
      - trimesh==3.21.7
      - typed-argument-parser==1.10.1
      - typeguard==4.2.1
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.10.0
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - uri-template==1.3.0
      - varname==0.13.0
      - velruse==1.1.1
      - venusian==3.1.0
      - vision-aided-loss==0.1.0
      - wandb==0.15.3
      - wcwidth==0.2.6
      - webcolors==1.13
      - webdataset==0.2.86
      - webencodings==0.5.1
      - webob==1.8.8
      - websocket-client==1.6.2
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.10
      - wtforms==3.1.2
      - wtforms-recaptcha==0.3.2
      - xatlas==0.0.9
      - xformers==0.0.18
      - xxhash==3.5.0
      - yapf==0.33.0
      - yarg==0.1.9
      - yarl==1.9.4
      - zipp==3.15.0
      - zope-deprecation==5.0
      - zope-interface==7.0.3
      - zope-sqlalchemy==3.1
      # - flash-attn==2.6.3
